name: 编译x86

on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: 检查代码仓库
        uses: actions/checkout@v3
      - 
        name: 编译
        run: |
          cat >>~/.cargo/config <<EOF
          [target.x86_64-unknown-linux-musl]
          rustflags = ["-C", "target-feature=+crt-static","-C", "strip=symbols"]
          EOF
          sudo apt-get update && sudo apt-get install -qq musl-tools
          rustup target add x86_64-unknown-linux-musl
          git clone https://github.com/lbl8603/vnt.git /opt/vnt
          cd /opt/vnt
          cargo build --package vnt-cli --target=x86_64-unknown-linux-musl --release --features openssl-vendored
      - name : 上传
        uses: actions/upload-artifact@master
        if: always()
        with:
         name: vnt-cli
         path: /opt/vnt/target/x86_64-unknown-linux-musl/release/vnt-cli
